export const response = {
  location: {
    address: "경기 용인시 기흥구 동백1로 31",
  },
  stationInfo: {
    "초당중학교.삼부르네상스아파트": {
      lon: "127.158489",
      lat: "37.264847",
      stationId: "228000174",
    },
    "두산위브더제니스.호수마을.자연엔데시앙": {
      lon: "127.150714",
      lat: "37.285067",
      stationId: "228000157",
    },
    "신논현역.주류성빌딩": {
      lon: "127.02585277777777",
      lat: "37.501063888888886",
      stationId: null,
    },
    "동백고.풍림코아루.호수마을서해그랑블": {
      lon: "127.158789",
      lat: "37.281531",
      stationId: "228000168",
    },
    도착지: {
      lon: "127.02585277777777",
      lat: "37.501063888888886",
      stationId: null,
    },
    동백경남아너스빌: {
      lon: "127.157042",
      lat: "37.267119",
      stationId: "228000173",
    },
    동백중학교: {
      lon: "127.158836",
      lat: "37.284814",
      stationId: "228000148",
    },
    "동백소방서.동일하이빌.롯데캐슬": {
      lon: "127.155367",
      lat: "37.278150",
      stationId: "228000169",
    },
    동백2동행정복지센터: {
      lon: "127.151764",
      lat: "37.272072",
      stationId: "228000171",
    },
    수원컨트리클럽: {
      lon: "127.119406",
      lat: "37.275944",
      stationId: "228000683",
    },
    "강남대역.강남대입구": {
      lon: "127.125531",
      lat: "37.271228",
      stationId: "228000684",
    },
    기흥역: {
      lon: "127.114586",
      lat: "37.275964",
      stationId: "228000682",
    },
    어정역: {
      lon: "127.143625",
      lat: "37.275525",
      stationId: "228000143",
    },
    어정풍림아파트: {
      lon: "127.138806",
      lat: "37.273736",
      stationId: "228000142",
    },
    "롯데캐슬스카이.이안두드림.백남준아트센터": {
      lon: "127.108803",
      lat: "37.271881",
      stationId: "228000681",
    },
    "어정삼거리.강남마을": {
      lon: "127.129758",
      lat: "37.268681",
      stationId: "228000685",
    },
    갈천마을: {
      lon: "127.137311",
      lat: "37.272003",
      stationId: "228000141",
    },
    출발지: {
      lon: "127.1598472470739",
      lat: "37.26497823618022",
      stationId: null,
    },
    "동백역.성산마을서해그랑블": {
      lon: "127.154003",
      lat: "37.270711",
      stationId: "228000172",
    },
    "상미마을.신갈오거리.롯데캐슬레이시티": {
      lon: "127.103583",
      lat: "37.271067",
      stationId: "228000680",
    },
    "동막초등학교.호수마을계룡리슈빌.어울림": {
      lon: "127.154983",
      lat: "37.285397",
      stationId: "228000147",
    },
    동백이마트: {
      lon: "127.151519",
      lat: "37.279044",
      stationId: "228000155",
    },
    지석역: {
      lon: "127.134875",
      lat: "37.269475",
      stationId: "228002137",
    },
    쥬네브상가: {
      lon: "127.151703",
      lat: "37.275281",
      stationId: "228000170",
    },
  },
  InfoList: [
    {
      summary: {
        taxiFare: 6400,
        wastedTime: 3357,
        savedTime: 1392,
        savedMoney: 43400,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 468,
          route: null,
          routeId: null,
          stationList: ["출발지", "갈천마을"],
        },
        {
          mode: "BUS",
          sectionTime: 2820,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 6700,
        wastedTime: 3338,
        savedTime: 1411,
        savedMoney: 43100,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 509,
          route: null,
          routeId: null,
          stationList: ["출발지", "지석역"],
        },
        {
          mode: "BUS",
          sectionTime: 2700,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 6100,
        wastedTime: 3446,
        savedTime: 1303,
        savedMoney: 43700,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 437,
          route: null,
          routeId: null,
          stationList: ["출발지", "어정풍림아파트"],
        },
        {
          mode: "BUS",
          sectionTime: 2880,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 5400,
        wastedTime: 3644,
        savedTime: 1105,
        savedMoney: 44400,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 395,
          route: null,
          routeId: null,
          stationList: ["출발지", "동백이마트"],
        },
        {
          mode: "BUS",
          sectionTime: 3180,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7600,
        wastedTime: 3287,
        savedTime: 1462,
        savedMoney: 42200,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 638,
          route: null,
          routeId: null,
          stationList: ["출발지", "강남대역.강남대입구"],
        },
        {
          mode: "BUS",
          sectionTime: 2580,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 6100,
        wastedTime: 3592,
        savedTime: 1157,
        savedMoney: 43700,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 523,
          route: null,
          routeId: null,
          stationList: ["출발지", "어정역"],
        },
        {
          mode: "BUS",
          sectionTime: 3060,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7200,
        wastedTime: 3348,
        savedTime: 1401,
        savedMoney: 42600,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 579,
          route: null,
          routeId: null,
          stationList: ["출발지", "어정삼거리.강남마을"],
        },
        {
          mode: "BUS",
          sectionTime: 2640,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 6100,
        wastedTime: 3889,
        savedTime: 860,
        savedMoney: 43700,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 520,
          route: null,
          routeId: null,
          stationList: ["출발지", "두산위브더제니스.호수마을.자연엔데시앙"],
        },
        {
          mode: "BUS",
          sectionTime: 3300,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7500,
        wastedTime: 4264,
        savedTime: 485,
        savedMoney: 42300,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 775,
          route: null,
          routeId: null,
          stationList: ["출발지", "동막초등학교.호수마을계룡리슈빌.어울림"],
        },
        {
          mode: "BUS",
          sectionTime: 3360,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 7200,
        wastedTime: 4249,
        savedTime: 500,
        savedMoney: 42600,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 700,
          route: null,
          routeId: null,
          stationList: ["출발지", "동백중학교"],
        },
        {
          mode: "BUS",
          sectionTime: 3540,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 6300,
        wastedTime: 4262,
        savedTime: 487,
        savedMoney: 43500,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 533,
          route: null,
          routeId: null,
          stationList: ["출발지", "동백고.풍림코아루.호수마을서해그랑블"],
        },
        {
          mode: "BUS",
          sectionTime: 3660,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동백고.풍림코아루.호수마을서해그랑블",
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 5600,
        wastedTime: 4255,
        savedTime: 494,
        savedMoney: 44200,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 406,
          route: null,
          routeId: null,
          stationList: ["출발지", "동백소방서.동일하이빌.롯데캐슬"],
        },
        {
          mode: "BUS",
          sectionTime: 3780,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동백소방서.동일하이빌.롯데캐슬",
            "동백고.풍림코아루.호수마을서해그랑블",
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 5000,
        wastedTime: 4266,
        savedTime: 483,
        savedMoney: 44800,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 297,
          route: null,
          routeId: null,
          stationList: ["출발지", "쥬네브상가"],
        },
        {
          mode: "BUS",
          sectionTime: 3840,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "쥬네브상가",
            "동백소방서.동일하이빌.롯데캐슬",
            "동백고.풍림코아루.호수마을서해그랑블",
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 4800,
        wastedTime: 4423,
        savedTime: 326,
        savedMoney: 45000,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 334,
          route: null,
          routeId: null,
          stationList: ["출발지", "동백역.성산마을서해그랑블"],
        },
        {
          mode: "BUS",
          sectionTime: 4020,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동백역.성산마을서해그랑블",
            "동백2동행정복지센터",
            "쥬네브상가",
            "동백소방서.동일하이빌.롯데캐슬",
            "동백고.풍림코아루.호수마을서해그랑블",
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 5300,
        wastedTime: 4537,
        savedTime: 212,
        savedMoney: 44500,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 508,
          route: null,
          routeId: null,
          stationList: ["출발지", "동백2동행정복지센터"],
        },
        {
          mode: "BUS",
          sectionTime: 3900,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동백2동행정복지센터",
            "쥬네브상가",
            "동백소방서.동일하이빌.롯데캐슬",
            "동백고.풍림코아루.호수마을서해그랑블",
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 4800,
        wastedTime: 4341,
        savedTime: 408,
        savedMoney: 45000,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 132,
          route: null,
          routeId: null,
          stationList: ["출발지", "동백경남아너스빌"],
        },
        {
          mode: "BUS",
          sectionTime: 4080,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "동백경남아너스빌",
            "동백역.성산마을서해그랑블",
            "동백2동행정복지센터",
            "쥬네브상가",
            "동백소방서.동일하이빌.롯데캐슬",
            "동백고.풍림코아루.호수마을서해그랑블",
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
    {
      summary: {
        taxiFare: 4800,
        wastedTime: 4337,
        savedTime: 412,
        savedMoney: 45000,
      },
      steps: [
        {
          mode: "TAXI",
          sectionTime: 68,
          route: null,
          routeId: null,
          stationList: ["출발지", "초당중학교.삼부르네상스아파트"],
        },
        {
          mode: "BUS",
          sectionTime: 4080,
          route: "직행좌석:5003B",
          routeId: "228000182",
          stationList: [
            "초당중학교.삼부르네상스아파트",
            "동백경남아너스빌",
            "동백역.성산마을서해그랑블",
            "동백2동행정복지센터",
            "쥬네브상가",
            "동백소방서.동일하이빌.롯데캐슬",
            "동백고.풍림코아루.호수마을서해그랑블",
            "동백중학교",
            "동막초등학교.호수마을계룡리슈빌.어울림",
            "두산위브더제니스.호수마을.자연엔데시앙",
            "동백이마트",
            "어정역",
            "어정풍림아파트",
            "갈천마을",
            "지석역",
            "어정삼거리.강남마을",
            "강남대역.강남대입구",
            "수원컨트리클럽",
            "기흥역",
            "롯데캐슬스카이.이안두드림.백남준아트센터",
            "상미마을.신갈오거리.롯데캐슬레이시티",
            "신논현역.주류성빌딩",
          ],
        },
        {
          mode: "WALK",
          sectionTime: 14,
          route: null,
          routeId: null,
          stationList: ["신논현역.주류성빌딩", "도착지1"],
        },
      ],
    },
  ],
};
